"""Add SpecialItem model

Revision ID: 68fb469e511e
Revises: 
Create Date: 2024-07-11 15:01:01.745125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fb469e511e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_item')
    # ### end Alembic commands ###
